## Database Properties
spring.datasource.url=jdbc:mysql:///users-db?cloudSqlInstance=users-db:us-central1:users-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=users-db&password=Socrates7612!&useSSL=FALSE

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

